# Background

# Data

The data for this data set was pulled from here on kaggle old: https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset


new and cleaned: 
https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset


challenge: https://www.kaggle.com/datasets/cdc/behavioral-risk-factor-surveillance-system

https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf

In [3]:
import numpy as np
import pandas as pd

In [4]:
dia_df = pd.read_csv('diabetes_health_indicators/diabetes_012_health_indicators_BRFSS2015.csv')

dia_df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [5]:
dia_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  MentHlth              253680 non-null  float64
 16  PhysHlth              253680 non-null  float64
 17  DiffWalk              253680 non-null  float64
 18  Sex                   253680 non-null  float64
 19  Age                   253680 non-null  float64
 20  Education             253680 non-null  float64
 21  Income                253680 non-null  float64
dtypes: float64(22)
memory usage: 42.6 MB

In [6]:
dia_df.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [29]:
dia_bf_df = pd.read_csv('BRFSS_2015/2015.csv')

In [30]:
dia_bf_df.columns

Index(['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE',
       'SEQNO', '_PSU', 'CTELENUM',
       ...
       '_PAREC1', '_PASTAE1', '_LMTACT1', '_LMTWRK1', '_LMTSCL1', '_RFSEAT2',
       '_RFSEAT3', '_FLSHOT6', '_PNEUMO2', '_AIDTST3'],
      dtype='object', length=330)

In [31]:
#check that the data loaded in is in the correct format
pd.set_option('display.max_columns', 500)
dia_bf_df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18.0,10.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,70.0,178.0,12701.0,4018.0,4.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.700000e+01,33.0,6.700000e+01,33.0,17.0,100.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,50.0,217.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,4.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,2.0,6.0,1.0,2.0,NaN,2.0,2.0,3.0,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,1.0,28.781560,NaN,NaN,NaN,NaN,9.0,NaN,108.060903,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,52.0,4.0,68.0,173.0,7484.0,2509.0,3.0,2.0,1.0,4.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,7.000000e+00,17.0,7.000000e+00,29.0,29.0,13.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,24.0,78.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,5.397605e-79,2876.0,493.0,1.0,5.397605e-79,60.0,60.0,2800.0,2800.0,168.0,5.397605e-79,5.397605e-79,5.397605e-79,168.0,5.397605e-79,168.0,5.397605e-79,5.397605e-79,5.397605e-79,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,2.0
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88.0,88.0,1.0,2.0,2.0,1.0,3.0,NaN,1.0,1.0,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,2.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,1.0,0.614125,255.264797,2.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,71.0,6.0,71.0,180.0,7167.0,2204.0,2.0,1.0,1.0,2.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,2173.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,30.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,67.0,170.0,8165.0,2819.0,3.0,2.0,2.0,2.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,100.0,5.397605e-79,3.0,3.0,14.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,100.0,20.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,9.0
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88.0,30.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,1.0,5.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,9.0,NaN,258.682223,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,61.0,5.0,64.0,163.0,6441.0,2437.0,2.0,1.0,1.0,3.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,200.0,4.300000e+01,57.0,33.0,67.0,1.000000e+00,5.397605e-79,5.397605e-79,1.000000e+00,NaN,200.0,9.0,1.0,1.0,1.0,1.000000e+00,5.397605e-79,2.0,NaN,NaN,2543.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0

In [32]:
# There are 330 columns which are too much to compute with the resources/time available
# Picking columns related to diabetes

dia_cols_selected = ['DIABETE3','_RFHYPE5',  
                                         'ASTHMA3','TOLDHI2', '_CHOLCHK', 
                                         '_BMI5', 
                                         'SMOKE100', 
                                         'CVDSTRK3', '_MICHD', 
                                         '_TOTINDA', 
                                         '_FRTLT1', '_VEGLT1', 
                                         '_RFDRHV5','ALCDAY5' ,'AVEDRNK2','PAINACT2',
                                         'HLTHPLN1', 'MEDCOST' ,
                                         'GENHLTH', 'MENTHLTH','EMPLOY1' ,'PHYSHLTH', 'DIFFWALK', 
                                         'SEX', '_AGEG5YR','CHCOCNCR', 'EDUCA','WEIGHT2' ,'INCOME2' ]

In [33]:
dia_cols_df = dia_bf_df[dia_cols_selected]

dia_cols_df.shape

(441456, 29)

In [34]:
dia_cols_df.head()

,DIABETE3,_RFHYPE5,ASTHMA3,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_FRTLT1,_VEGLT1,_RFDRHV5,ALCDAY5,AVEDRNK2,PAINACT2,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,EMPLOY1,PHYSHLTH,DIFFWALK,SEX,_AGEG5YR,CHCOCNCR,EDUCA,WEIGHT2,INCOME2
0,3.0,2.0,1.0,1.0,1.0,4018.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,888.0,NaN,NaN,1.0,2.0,5.0,18.0,8.0,15.0,1.0,2.0,9.0,2.0,4.0,280.0,3.0
1,3.0,1.0,2.0,2.0,2.0,2509.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,888.0,NaN,NaN,2.0,1.0,3.0,88.0,3.0,88.0,2.0,2.0,7.0,2.0,6.0,165.0,1.0
2,3.0,1.0,2.0,1.0,1.0,2204.0,NaN,1.0,NaN,9.0,9.0,9.0,9.0,NaN,NaN,NaN,1.0,2.0,4.0,88.0,7.0,15.0,NaN,2.0,11.0,1.0,4.0,158.0,99.0
3,3.0,2.0,2.0,1.0,1.0,2819.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,888.0,NaN,NaN,1.0,1.0,5.0,30.0,8.0,30.0,1.0,2.0,9.0,1.0,4.0,180.0,8.0
4,3.0,1.0,2.0,2.0,1.0,2437.0,2.0,2.0,2.0,2.0,9.0,1.0,1.0,888.0,NaN,NaN,1.0,2.0,5.0,88.0,8.0,20.0,2.0,2.0,9.0,2.0,5.0,142.0,77.0

In [35]:
dia_cols_df.isna().sum()

DIABETE3         7
_RFHYPE5         0
ASTHMA3          0
TOLDHI2      59154
_CHOLCHK         0
_BMI5        36398
SMOKE100     14255
CVDSTRK3         0
_MICHD        3942
_TOTINDA         0
_FRTLT1          0
_VEGLT1          0
_RFDRHV5         0
ALCDAY5      15931
AVEDRNK2    230618
PAINACT2    441456
HLTHPLN1         0
MEDCOST          1
GENHLTH          2
MENTHLTH         0
EMPLOY1          0
PHYSHLTH         1
DIFFWALK     12334
SEX              0
_AGEG5YR         0
CHCOCNCR         0
EDUCA            0
WEIGHT2       5315
INCOME2       3301
dtype: int64

In [36]:
# Find percentage of values missing in each column

dia_cols_df.isna().sum()/dia_cols_df.shape[0]*100

DIABETE3      0.001586
_RFHYPE5      0.000000
ASTHMA3       0.000000
TOLDHI2      13.399750
_CHOLCHK      0.000000
_BMI5         8.244989
SMOKE100      3.229087
CVDSTRK3      0.000000
_MICHD        0.892954
_TOTINDA      0.000000
_FRTLT1       0.000000
_VEGLT1       0.000000
_RFDRHV5      0.000000
ALCDAY5       3.608740
AVEDRNK2     52.240314
PAINACT2    100.000000
HLTHPLN1      0.000000
MEDCOST       0.000227
GENHLTH       0.000453
MENTHLTH      0.000000
EMPLOY1       0.000000
PHYSHLTH      0.000227
DIFFWALK      2.793936
SEX           0.000000
_AGEG5YR      0.000000
CHCOCNCR      0.000000
EDUCA         0.000000
WEIGHT2       1.203970
INCOME2       0.747753
dtype: float64

In [37]:
# Drop columns average drink and painact since over 50% off the data is missing

# Drop the rest off the rows. Normally for _VegeSym and TOLDHI2 would replace with the mean or most common values

# However, due to the significant number of rows (440K) and the computing limits off the machine, we are dropping all the rows

In [38]:
dia_cols_df = dia_cols_df.drop(['AVEDRNK2','PAINACT2'],axis=1)

dia_cols_df.shape

(441456, 27)

In [39]:
# Drop NA in rows reduce data size to process on current computing power

dia_cols_df = dia_cols_df.dropna()

dia_cols_df.shape

(342456, 27)

Citing the process here of cleaning the data columns

https://www.kaggle.com/code/alexteboul/diabetes-health-indicators-dataset-notebook/notebook

Column: 117 SAS Variable Name: DIABETE3
Prologue:
Description: (Ever told) you have diabetes (If "Yes" and respondent is female, ask "Was this only when you were pregnant?". If
Respondent says pre-diabetes or borderline diabetes, use response code 4.)
Value Value Label Frequency Percentage
Weighted
Percentage
1 Yes 57,256 12.97 10.48
2 Yes, but female told only during pregnancy----Go to Section 07.7.1
SEX
3,608 0.82 0.95
3 No----Go to Section 07.7.1 SEX 372,104 84.29 86.77
4 No, pre-diabetes or borderline diabetes----Go to Section 07.7.1 SEX 7,690 1.74 1.60
7 Donâ€™t know/Not Sure----Go to Section 07.7.1 SEX 598 0.14 0.16
9 Refused----Go to Section 07.7.1 SEX 193 0.04 0.04

In [40]:
# Strategy for column DIABETE3
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)

dia_cols_df['DIABETE3'] = dia_cols_df['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
dia_cols_df = dia_cols_df[dia_cols_df.DIABETE3 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.DIABETE3 != 9]
dia_cols_df.DIABETE3.unique()

array([0., 2., 1.])

In [41]:
#1 _RFHYPE5
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
dia_cols_df['_RFHYPE5'] = dia_cols_df['_RFHYPE5'].replace({1:0, 2:1})
dia_cols_df = dia_cols_df[dia_cols_df._RFHYPE5 != 9]
dia_cols_df._RFHYPE5.unique()

array([1., 0.])

In [42]:
#2 TOLDHI2
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
dia_cols_df['TOLDHI2'] = dia_cols_df['TOLDHI2'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.TOLDHI2 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.TOLDHI2 != 9]
dia_cols_df.TOLDHI2.unique()

array([1., 0.])

In [43]:
#3 _CHOLCHK
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9
dia_cols_df['_CHOLCHK'] = dia_cols_df['_CHOLCHK'].replace({3:0,2:0})
dia_cols_df = dia_cols_df[dia_cols_df._CHOLCHK != 9]
dia_cols_df._CHOLCHK.unique()

array([1., 0.])

In [44]:
#4 _BMI5 (no changes, just note that these are BMI * 100. So for example a BMI of 4018 is really 40.18)
dia_cols_df['_BMI5'] = dia_cols_df['_BMI5'].div(100).round(0)
dia_cols_df._BMI5.unique()

array([40., 25., 28., 24., 27., 30., 26., 23., 34., 33., 21., 22., 31.,
       38., 20., 19., 32., 46., 41., 37., 36., 29., 35., 18., 54., 45.,
       39., 47., 43., 55., 49., 42., 17., 16., 48., 44., 50., 59., 15.,
       52., 53., 57., 51., 14., 58., 63., 61., 56., 60., 74., 62., 64.,
       13., 66., 73., 65., 68., 85., 71., 84., 67., 70., 82., 79., 92.,
       72., 88., 96., 81., 12., 77., 95., 75., 91., 69., 76., 87., 89.,
       83., 98., 86., 80., 90., 78., 97.])

In [45]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
dia_cols_df['SMOKE100'] = dia_cols_df['SMOKE100'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.SMOKE100 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.SMOKE100 != 9]
dia_cols_df.SMOKE100.unique()

array([1., 0.])

In [46]:
#6 CVDSTRK3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
dia_cols_df['CVDSTRK3'] = dia_cols_df['CVDSTRK3'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.CVDSTRK3 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.CVDSTRK3 != 9]
dia_cols_df.CVDSTRK3.unique()

array([0., 1.])

In [47]:
#7 _MICHD
#Change 2 to 0 because this means did not have MI or CHD
dia_cols_df['_MICHD'] = dia_cols_df['_MICHD'].replace({2: 0})
dia_cols_df._MICHD.unique()

array([0., 1.])

In [48]:
#8 _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
dia_cols_df['_TOTINDA'] = dia_cols_df['_TOTINDA'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df._TOTINDA != 9]
dia_cols_df._TOTINDA.unique()

array([0., 1.])

In [49]:
#9 _FRTLT1
# Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# remove all dont knows and missing 9
dia_cols_df['_FRTLT1'] = dia_cols_df['_FRTLT1'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df._FRTLT1 != 9]
dia_cols_df._FRTLT1.unique()

array([0., 1.])

In [50]:
#10 _VEGLT1
# Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# remove all dont knows and missing 9
dia_cols_df['_VEGLT1'] = dia_cols_df['_VEGLT1'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df._VEGLT1 != 9]
dia_cols_df._VEGLT1.unique()

array([1., 0.])

In [51]:
#11 _RFDRHV5
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
dia_cols_df['_RFDRHV5'] = dia_cols_df['_RFDRHV5'].replace({1:0, 2:1})
dia_cols_df = dia_cols_df[dia_cols_df._RFDRHV5 != 9]
dia_cols_df._RFDRHV5.unique()

array([0., 1.])

In [52]:
#12 HLTHPLN1
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
dia_cols_df['HLTHPLN1'] = dia_cols_df['HLTHPLN1'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.HLTHPLN1 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.HLTHPLN1 != 9]
dia_cols_df.HLTHPLN1.unique()

array([1., 0.])

In [53]:
#13 MEDCOST
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
dia_cols_df['MEDCOST'] = dia_cols_df['MEDCOST'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.MEDCOST != 7]
dia_cols_df = dia_cols_df[dia_cols_df.MEDCOST != 9]
dia_cols_df.MEDCOST.unique()

array([0., 1.])

In [54]:
#14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
dia_cols_df = dia_cols_df[dia_cols_df.GENHLTH != 7]
dia_cols_df = dia_cols_df[dia_cols_df.GENHLTH != 9]
dia_cols_df.GENHLTH.unique()

array([5., 3., 2., 4., 1.])

In [55]:
#15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
dia_cols_df['MENTHLTH'] = dia_cols_df['MENTHLTH'].replace({88:0})
dia_cols_df = dia_cols_df[dia_cols_df.MENTHLTH != 77]
dia_cols_df = dia_cols_df[dia_cols_df.MENTHLTH != 99]
dia_cols_df.MENTHLTH.unique()

array([18.,  0., 30.,  3.,  5., 15., 10.,  6., 20.,  2., 25.,  1., 29.,
        4.,  7.,  8., 21., 14., 26.,  9., 16., 28., 11., 12., 24., 17.,
       13., 23., 27., 19., 22.])

In [56]:
#16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
dia_cols_df['PHYSHLTH'] = dia_cols_df['PHYSHLTH'].replace({88:0})
dia_cols_df = dia_cols_df[dia_cols_df.PHYSHLTH != 77]
dia_cols_df = dia_cols_df[dia_cols_df.PHYSHLTH != 99]
dia_cols_df.PHYSHLTH.unique()

array([15.,  0., 30.,  2., 14., 28.,  7., 20.,  3., 10.,  1.,  5., 17.,
        4., 19.,  6., 21., 12.,  8., 25., 27., 22., 29., 24.,  9., 16.,
       18., 23., 13., 26., 11.])

In [57]:
#17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
dia_cols_df['DIFFWALK'] = dia_cols_df['DIFFWALK'].replace({2:0})
dia_cols_df = dia_cols_df[dia_cols_df.DIFFWALK != 7]
dia_cols_df = dia_cols_df[dia_cols_df.DIFFWALK != 9]
dia_cols_df.DIFFWALK.unique()

array([1., 0.])

In [58]:
#18 SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
dia_cols_df['SEX'] = dia_cols_df['SEX'].replace({2:0})
dia_cols_df.SEX.unique()

array([0., 1.])

In [59]:
#19 _AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
dia_cols_df = dia_cols_df[dia_cols_df._AGEG5YR != 14]
dia_cols_df._AGEG5YR.unique()

array([ 9.,  7., 11., 10., 13.,  8.,  4.,  6.,  2., 12.,  5.,  1.,  3.])

In [60]:
#20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
dia_cols_df = dia_cols_df[dia_cols_df.EDUCA != 9]
dia_cols_df.EDUCA.unique()

array([4., 6., 3., 5., 2., 1.])

In [61]:
#21 INCOME2
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
dia_cols_df = dia_cols_df[dia_cols_df.INCOME2 != 77]
dia_cols_df = dia_cols_df[dia_cols_df.INCOME2 != 99]
dia_cols_df.INCOME2.unique()

array([3., 1., 8., 6., 4., 7., 2., 5.])

Now that we've applied some of cleaning recommendations here. We are going to clean the rest off the columns that the source did not cover

In [62]:
dia_cols_df.head(10)

,DIABETE3,_RFHYPE5,ASTHMA3,TOLDHI2,_CHOLCHK,_BMI5,SMOKE100,CVDSTRK3,_MICHD,_TOTINDA,_FRTLT1,_VEGLT1,_RFDRHV5,ALCDAY5,HLTHPLN1,MEDCOST,GENHLTH,MENTHLTH,EMPLOY1,PHYSHLTH,DIFFWALK,SEX,_AGEG5YR,CHCOCNCR,EDUCA,WEIGHT2,INCOME2
0,0.0,1.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,888.0,1.0,0.0,5.0,18.0,8.0,15.0,1.0,0.0,9.0,2.0,4.0,280.0,3.0
1,0.0,0.0,2.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,888.0,0.0,1.0,3.0,0.0,3.0,0.0,0.0,0.0,7.0,2.0,6.0,165.0,1.0
3,0.0,1.0,2.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,888.0,1.0,1.0,5.0,30.0,8.0,30.0,1.0,0.0,9.0,1.0,4.0,180.0,8.0
5,0.0,1.0,2.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,888.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,11.0,2.0,3.0,145.0,6.0
6,0.0,1.0,2.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,203.0,1.0,0.0,2.0,3.0,7.0,0.0,0.0,0.0,11.0,2.0,5.0,148.0,4.0
9,0.0,1.0,2.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,888.0,1.0,0.0,2.0,0.0,7.0,2.0,0.0,1.0,10.0,2.0,6.0,161.0,8.0
10,0.0,1.0,2.0,0.0,1.0,30.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,888.0,1.0,0.0,3.0,0.0,7.0,14.0,0.0,0.0,9.0,2.0,6.0,175.0,7.0
15,0.0,1.0,1.0,1.0,1.0,25.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,202.0,1.0,0.0,3.0,0.0,5.0,0.0,1.0,0.0,11.0,2.0,4.0,128.0,4.0
16,2.0,1.0,2.0,1.0,1.0,30.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,888.0,1.0,0.0,5.0,30.0,8.0,30.0,1.0,0.0,9.0,1.0,5.0,200.0,1.0
19,0.0,0.0,2.0,0.0,1.0,24.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,888.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,8.0,2.0,4.0,163.0,3.0

In [63]:
#22 ALCDAY5
# Purpose is too incorporate alcohol consumption in model
# 101 - 299 is 1
# 777 and 888 is 0
# Remove 999

dia_cols_df = dia_cols_df[dia_cols_df.ALCDAY5 != 999]
dia_cols_df['ALCDAY5'] = dia_cols_df['ALCDAY5'].replace({777:0, 888:0})
dia_cols_df.loc[(dia_cols_df['ALCDAY5'] > 100) & (dia_cols_df['ALCDAY5'] < 300),'ALCDAY5'] = 1
dia_cols_df.ALCDAY5.unique()

array([0., 1.])

In [64]:
#23 WEIGHT2

# 50 - 0999: This is the persons weight in pounds.
# 7777: Means not sure. Remove value
# 9000 - 9998: Value after first 9 is weight in kilograms. Convert to pounds.
# 9999: Remove number


dia_cols_df = dia_cols_df[dia_cols_df.WEIGHT2 != 7777]
dia_cols_df = dia_cols_df[dia_cols_df.WEIGHT2 != 9999]
#dia_cols_df['WEIGHT2'] = (dia_cols_df.loc[dia_cols_df['WEIGHT2'] > 8999,'WEIGHT2']-9000)*2.2

In [65]:
dia_cols_df.loc[dia_cols_df['WEIGHT2'] > 8999,'WEIGHT2'] = np.round((dia_cols_df.loc[dia_cols_df['WEIGHT2'] > 8999,'WEIGHT2']-9000) *2.205,0)
dia_cols_df.WEIGHT2.unique()

array([280., 165., 180., 145., 148., 161., 175., 128., 200., 163., 172.,
       182., 130., 135., 230., 118., 195., 232., 160., 140., 290., 196.,
       266., 215., 138., 150., 143., 190., 156., 256., 185., 159., 205.,
       146., 260., 134., 240., 131., 120., 265., 192., 220., 168., 162.,
       245., 126., 189., 122., 170., 210., 125., 250., 193., 155., 186.,
       208., 275., 225., 153.,  99., 142., 141., 136., 164., 214., 127.,
       147., 152., 100., 229., 295., 173., 103., 244., 179., 235., 198.,
       270., 178., 259., 350., 285., 219., 217., 117., 110., 284., 108.,
       139., 203., 166., 199., 202., 112., 228., 330., 121., 115., 223.,
       158., 218., 197., 132., 207., 129., 194., 151., 337., 177., 206.,
       176., 283., 300., 292., 211., 187., 109., 167.,  88., 119., 137.,
       249., 105., 204., 107., 325., 233., 258., 242., 209., 213., 124.,
       154., 183., 253., 149., 212., 357., 144.,  98., 255., 157., 174.,
       268., 267., 254., 370., 123., 320., 279., 236., 133., 340., 116.,
       191., 106.,  94.,  95., 184., 247., 216., 323., 310., 274., 262.,
       181., 286., 101., 222., 201., 188., 263., 171., 375., 288., 301.,
        81., 169., 114., 234., 239., 227., 328., 221., 430., 257., 252.,
       111., 238.,  80., 305., 241., 364., 291., 226.,  92., 237., 317.,
       282.,  90., 277., 335., 460., 248., 251., 352., 400., 261., 246.,
       303., 385., 343., 243., 318., 324., 312., 294., 102., 326., 380.,
       231., 302., 104., 264.,  97., 276., 272., 224., 308., 273., 360.,
       339., 297., 315., 390., 345., 269., 382., 113., 344., 420., 450.,
       374., 311., 333., 319.,  96., 289., 316., 398.,  79., 278.,  89.,
        85.,  93.,  77., 298., 307., 296., 293., 510., 314., 348., 410.,
       493., 309., 365.,  87., 299., 287.,  86., 338., 304., 271., 368.,
        82., 313., 405., 342., 522.,  70., 535., 388., 306., 378.,  83.,
       431., 332., 395.,  91., 331., 470., 363.,  75., 397., 471., 341.,
       424., 440., 576., 356., 507., 575.,  84., 504., 500., 371., 361.,
       281., 550., 396., 362., 355., 425., 408., 601., 322., 392., 372.,
       456., 386., 509.,  78., 418., 327., 359., 389., 351., 358., 346.,
       508., 604., 353., 384., 329., 486., 415., 354., 321., 476., 403.,
       458., 349., 485., 503., 502., 511., 506., 602., 505., 600., 409.,
       603., 501., 605., 607., 411., 517.,  76., 402., 455., 490., 334.,
       427., 391., 480., 347., 428., 387., 465., 399., 383., 437.,  65.,
       473., 639., 495., 442., 394.,  72., 467., 381., 422., 435., 421.,
       551., 412.,  68., 377., 540., 527., 367., 373., 457., 366., 393.,
       336., 453., 441., 432., 515., 560., 419., 584., 617., 573., 545.,
       376., 454.,  74., 570.])

In [66]:
dia_cols_df.EMPLOY1.unique()

array([8., 3., 2., 7., 5., 1., 9., 6., 4.])

In [67]:
#24 EMPLOY1

# remove value 9 refused
# Values 1 and 2 of employed and self-employed map to 1
# 3-4 map to 0 implying not currently working
# 5-8 are student, homemaker, retired, and unable to work. These are folks who don't need to work. This value maps to 2

dia_cols_df = dia_cols_df[dia_cols_df.EMPLOY1 != 9]
dia_cols_df['EMPLOY1'] = dia_cols_df['EMPLOY1'].replace({2:1, 3:0, 4:0, 5:2, 6:2, 7:2, 8:2})
dia_cols_df.EMPLOY1.unique()

array([2., 0., 1.])

In [68]:
#25 CHCOCNCR

# Data is close to ordinal
# remove values 7 and 9
# map 2 to 0

dia_cols_df = dia_cols_df[dia_cols_df.CHCOCNCR != 7]
dia_cols_df = dia_cols_df[dia_cols_df.CHCOCNCR != 9]
dia_cols_df['CHCOCNCR'] = dia_cols_df['CHCOCNCR'].replace({2:0})
dia_cols_df.CHCOCNCR.unique()

array([0., 1.])

In [69]:
#27 ASTHMA3

# Data is close to ordinal
# remove values 7 and 9
# map 2 to 0

dia_cols_df = dia_cols_df[dia_cols_df.ASTHMA3 != 7]
dia_cols_df = dia_cols_df[dia_cols_df.ASTHMA3 != 9]
dia_cols_df['ASTHMA3'] = dia_cols_df['ASTHMA3'].replace({2:0})
dia_cols_df.ASTHMA3.unique()

array([1., 0.])

In [70]:
#Rename the columns to make them more readable
diab_df = dia_cols_df.rename(columns = {'DIABETE3':'Diabetes_012', 
                                         '_RFHYPE5':'HighBP',  
                                         'TOLDHI2':'HighChol', '_CHOLCHK':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', 
                                         '_TOTINDA':'PhysActivity', 
                                         '_FRTLT1':'Fruits', '_VEGLT1':"Veggies", 
                                         '_RFDRHV5':'HvyAlcoholConsump', 
                                         'HLTHPLN1':'AnyHealthcare', 'MEDCOST':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 
                                         'SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME2':'Income', 
                                          'EMPLOY1':'Employed', 'CHCOCNCR':'Chronic_Cancer','ASTHMA3':'Asthma',
                                            'WEIGHT2':'Weight (lbs)'
                                       })
diab_df

,Diabetes_012,HighBP,Asthma,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,ALCDAY5,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,Employed,PhysHlth,DiffWalk,Sex,Age,Chronic_Cancer,Education,Weight (lbs),Income
0,0.0,1.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,5.0,18.0,2.0,15.0,1.0,0.0,9.0,0.0,4.0,280.0,3.0
1,0.0,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,6.0,165.0,1.0
3,0.0,1.0,0.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,5.0,30.0,2.0,30.0,1.0,0.0,9.0,1.0,4.0,180.0,8.0
5,0.0,1.0,0.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,11.0,0.0,3.0,145.0,6.0
6,0.0,1.0,0.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,11.0,0.0,5.0,148.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441450,0.0,1.0,0.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,5.0,0.0,1.0,5.0,0.0,6.0,360.0,7.0
441451,2.0,1.0,0.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,2.0,0.0,1.0,0.0,11.0,0.0,2.0,104.0,4.0
441452,0.0,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,5.0,160.0,2.0
441454,0.0,1.0,0.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,7.0,0.0,5.0,166.0,1.0
441455,2.0,1.0,0.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,9.0,0.0,6.0,135.0,2.0

In [71]:
diab_df.shape

(252189, 27)

We now have 252K rows

In [72]:
# Determine how many respondants have diabetes, pre-diabetes, or no diabetes

diab_df.groupby(['Diabetes_012']).size()

Diabetes_012
0.0    212478
1.0      4585
2.0     35126
dtype: int64

In [73]:
# Save Cleaned version of spreadsheet with pre-diabetes

diab_df.to_csv('diabetes_012_prediabetes_BRFSS2015.csv', sep=",", index=False)

# Create a Binary Classification of diabetes versus no diabetes

We will add the pre-diabetic patients to the diabetic patient category since pre-diabetes usually means that you are at risk for diabetes.

Even with adding them, there is still a huge class imbalance between the non - diabetic and diabetic patients.
There is a significant number of diabetic records to allow to make this a 50-50 split between the non-diabetic and diabetic patients.

In [74]:
diab_df_binary = diab_df

#Change the diabetics 2 to a 1 and pre-diabetics 1 to a 0, so that we have 0 meaning non-diabetic and pre-diabetic and 1 meaning diabetic.
diab_df_binary['Diabetes_012'] = diab_df_binary['Diabetes_012'].replace({1:0})
diab_df_binary['Diabetes_012'] = diab_df_binary['Diabetes_012'].replace({2:1})

#Change the column name to Diabetes_binary
diab_df_binary = diab_df_binary.rename(columns = {'Diabetes_012': 'Diabetes_binary'})
diab_df_binary.Diabetes_binary.unique()

array([0., 1.])

In [75]:
diab_df_binary.head()

,Diabetes_binary,HighBP,Asthma,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,ALCDAY5,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,Employed,PhysHlth,DiffWalk,Sex,Age,Chronic_Cancer,Education,Weight (lbs),Income
0,0.0,1.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,5.0,18.0,2.0,15.0,1.0,0.0,9.0,0.0,4.0,280.0,3.0
1,0.0,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,6.0,165.0,1.0
3,0.0,1.0,0.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,5.0,30.0,2.0,30.0,1.0,0.0,9.0,1.0,4.0,180.0,8.0
5,0.0,1.0,0.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,11.0,0.0,3.0,145.0,6.0
6,0.0,1.0,0.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,11.0,0.0,5.0,148.0,4.0

In [76]:
diab_df_binary.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    217063
1.0     35126
dtype: int64

In [77]:
#Separate the 0(No Diabetes) and 1&2(Pre-diabetes and Diabetes)
#Get the 1s
is1 = diab_df_binary['Diabetes_binary'] == 1
diab_df_bal_1 = diab_df_binary[is1]

#Get the 0s
is0 = diab_df_binary['Diabetes_binary'] == 0
diab_df_bal_0 = diab_df_binary[is0] 

#Select the 39977 random cases from the 0 (non-diabetes group). we already have 35126 cases from the diabetes risk group
diab_df_bal_0_rand1 = diab_df_bal_0.take(np.random.permutation(len(diab_df_bal_0))[:35126])

#Append the diabetic records to the randomly selected normal records
diab_bal = diab_df_bal_0_rand1.append(diab_df_bal_1, ignore_index = True)

In [78]:
diab_bal.head()

,Diabetes_binary,HighBP,Asthma,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,ALCDAY5,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,Employed,PhysHlth,DiffWalk,Sex,Age,Chronic_Cancer,Education,Weight (lbs),Income
0,0.0,0.0,0.0,0.0,1.0,22.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,0.0,0.0,1.0,9.0,0.0,4.0,180.0,8.0
1,0.0,1.0,0.0,1.0,1.0,23.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,3.0,0.0,2.0,1.0,1.0,1.0,11.0,0.0,6.0,160.0,6.0
2,0.0,0.0,0.0,1.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,1.0,21.0,0.0,0.0,7.0,0.0,6.0,152.0,7.0
3,0.0,1.0,0.0,1.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,12.0,1.0,6.0,189.0,7.0
4,0.0,0.0,0.0,0.0,1.0,30.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,10.0,0.0,5.0,185.0,5.0

In [79]:
diab_bal.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    35126
1.0    35126
dtype: int64

In [80]:
#Save the 50-50 balanced dataset to csv
#************************************************************************************************
diab_bal.to_csv('diabetes_binary_5050_DR_BRFSS2015.csv', sep=",", index=False)
#************************************************************************************************

#Also save the original binary dataset to csv
#************************************************************************************************
diab_df_binary.to_csv('diabetes_binary_DR_BRFSS2015.csv', sep=",", index=False)
#************************************************************************************************